Restaurant/urls.py
from django.conf.urls import url
from django.contrib import admin
from restaurant.views import *

urlpatterns = [
    url(r'^admin', admin.site.urls),
    url(r'^home$', HomeView.as_view(), name='home'),
    url(r'^about$', AboutView.as_view(), name='about'),
    url(r'^book$', BookSeatView.as_view(), name='book'),
    url(r'^menu$', MenuView.as_view(), name='menu'),
    url(r'^order', OrderView.as_view(), name='order'),
    url(r'^contact$', ContactView.as_view(), name='contact'),
    # url(r'^dish$', DishView.as_view(), name = 'dish'),
    # url(r'^ingredient$', IngredientView.as_view(), name = 'ingredient'),
    # url(r'^drinks$', DrinksView.as_view(), name='drinks'),

]

restaurant/models.py
from django.db import models
from django.utils.timezone import now
from django.core import validators

# Create your models here.

DRINK_TYPES = (
    (1, 'soft_drinks'),
    (2, 'drinks'),
    (3, 'wines'),
    (4, 'beer'),
    (5, 'juice'),
)

WINE_COLORS = (
    (1, 'white'),
    (2, 'rose'),
    (3, 'red'),
)

WINE_SWEETNESS = (
    (1, 'dry'),
    (2, 'sweet'),
    (3, 'semi-sweet'),
    (4, 'semi-dry'),
)

DRINK_VOLUME = (
    (1, 'by the glass'),
    (2, 'bottle'),
    (3, 'decanter'),
)


class Ingredient(models.Model):
    ingredient_name = models.CharField(max_length=64, verbose_name='składnik')

    def __str__(self):
        return '{}'.format(self.ingredient_name)

    class Meta:
        verbose_name = 'składnik'
        verbose_name_plural = 'składniki'


class Dish(models.Model):
    dish_name = models.CharField(max_length=150, verbose_name='danie')
    price = models.DecimalField(max_digits=5, decimal_places=1, verbose_name='cena')
    ingredient = models.ForeignKey(Ingredient)

    def __str__(self):
        return '{} {} {}'.format(self.dish_name, self.price, self.ingredient)

    class Meta:
        verbose_name = 'danie'
        verbose_name_plural = 'dania'


class Drinks(models.Model):
    drink_type = models.IntegerField(choices=DRINK_TYPES, null=True, blank=True, verbose_name='napoje typ')
    drink_volume = models.IntegerField(choices=DRINK_VOLUME, null=True, blank=True, verbose_name='objętość')
    wine_colors = models.IntegerField(choices=WINE_COLORS, null=True, blank=True, verbose_name='kolor wina')
    wine_sweetness = models.IntegerField(choices=WINE_SWEETNESS, null=True, blank=True, verbose_name='smak wina')
    drink_name = models.CharField(max_length=99, null=True, blank=True, verbose_name='napoje nazwa')
    price = models.DecimalField(max_digits=5, decimal_places=1, default=0.00, verbose_name='cena')

    def __str__(self):
        return '{} {} {} {} {} {} '.format(self.drink_type,
                                           self.drink_volume,
                                           self.wine_colors,
                                           self.wine_sweetness,
                                           self.drink_name,
                                           self.price)

    class Meta:
        verbose_name = 'napój'
        verbose_name_plural = 'napoje'


class Contact(models.Model):
    contact_details = models.CharField(max_length=99, null=True, verbose_name='Imię i nazwisko')
    email = models.EmailField(validators=[validators.EmailValidator], blank=True)
    phone_number = models.CharField(max_length=12, null=True, verbose_name='numer telefonu')
    subject = models.CharField(max_length=99, verbose_name='temat')
    content = models.TextField(verbose_name='treść')
    date_added = models.DateTimeField(default=now, verbose_name='wysłane')

    def __str__(self):
        return '{} {} {} {} {} {}'.format(self.contact_details,
                                          self.email,
                                          self.phone_number,
                                          self.subject,
                                          self.content,
                                          self.date_added
                                          )

    class Meta:
        verbose_name = 'kontakt'
        verbose_name_plural = 'kontakty'


class Order(models.Model):
    name_surname = models.CharField(max_length=99, verbose_name='imię nazwisko')
    address = models.CharField(max_length=199, verbose_name='adres')
    email = models.EmailField(verbose_name='email')
    phone_number = models.CharField(max_length=20, verbose_name='numer telefonu')
    self_pickup = models.BooleanField(verbose_name='odbiór własny')
    dish = models.ManyToManyField(Dish, verbose_name='danie')
    drink = models.ManyToManyField(Drinks, verbose_name='napój')
    date_added = models.DateTimeField(default=now, verbose_name='wysłane')
    dish_order_quantity = models.CharField(max_length=10, verbose_name=' danie główne ilość', default=0)
    drink_order_quantity = models.CharField(max_length=10, verbose_name='drink ilość', default=0)
    wine_order_quantity = models.CharField(max_length=10, verbose_name='wino ilość', default=0)
    juice_order_quantity = models.CharField(max_length=10, verbose_name='sok ilość', default=0)
    beer_order_quantity = models.CharField(max_length=10, verbose_name='piwo ilość', default=0)

    def __str__(self):
        return '{} {} {} {} {} {} {} {} {} {} {} {}'.format(self.name_surname,
                                                               self.address,
                                                               self.email,
                                                               self.phone_number,
                                                               self.self_pickup,
                                                               # self.dish,
                                                               self.drink,
                                                               self.date_added,
                                                               self.dish_order_quantity,
                                                               self.drink_order_quantity,
                                                               self.wine_order_quantity,
                                                               self.juice_order_quantity,
                                                               self.beer_order_quantity,
                                                               )

    class Meta:
        verbose_name = 'zamówienie'
        verbose_name_plural = 'zamówienia'


class BookSeat(models.Model):
    date = models.DateTimeField(verbose_name='data rezerwacji')
    time = models.TimeField(verbose_name='godzina rezerwacji')
    guest_number = models.IntegerField(verbose_name='ilość gości')
    name_surname = models.CharField(max_length=60, verbose_name='imię, nazwisko')
    email = models.CharField(max_length=90, verbose_name='email')
    phone = models.CharField(max_length=15, verbose_name='numer telefonu')
    message = models.TextField(verbose_name="wiadomość")

    def __str__(self):
        return '{} {} {} {} {} {} {}'.format(self.date,
                                             self.time,
                                             self.guest_number,
                                             self.name_surname,
                                             self.email,
                                             self.phone,
                                             self.message)

    class Meta:
        verbose_name = 'rezerwacja'
        verbose_name_plural = 'rezerwacje'

restaurant/forms.py
from django.forms import ModelForm
from .models import *
from django import forms


class DishForm(ModelForm):
    class Meta:
        model = Dish
        fields = "__all__"



class IngredientForm(ModelForm):
    class Meta:
        model = Ingredient
        fields = "__all__"


class DrinksForm(ModelForm):
    class Meta:
        model = Drinks
        fields = "__all__"

class ContactForm(ModelForm):
    class Meta:
        model = Contact
        fields = "__all__"
        exclude = ['date_added']

class OrderForm(ModelForm):
    class Meta:
        model = Order
        exclude = ['dish', 'drink', 'date_added', 'dish_order_quantity', 'wine_order_quantity', 'juice_order_quantity', 'beer_order_quantity', 'drink_order_quantity']


class BookSeatForm(ModelForm):
    class Meta:
        model = BookSeat
        fields = "__all__"
        widgets = {
            'date': forms.TextInput(attrs={'placeholder': 'RRRR-MM-DD'}),
            'time': forms.TextInput(attrs={'placeholder': 'GG:MM'})

        }

restaurant/views.py
from django.shortcuts import render, redirect
from .forms import *
from .models import *
from django.views import View


class HomeView(View):

    def get(self, request):
        return render(request, 'home.html')


class MenuView(View):

    def get(self, request):
        dishes = Dish.objects.all()
        wines = Drinks.objects.filter(drink_type=3)
        beers = Drinks.objects.filter(drink_type=4)
        juices = Drinks.objects.filter(drink_type=5)
        soft_drinks = Drinks.objects.filter(drink_type=1)
        drinks = Drinks.objects.filter(drink_type=2)
        return render(request, 'menu.html', {'dishes': dishes,
                                             'drinks': drinks,
                                             'wines': wines,
                                             'beers': beers,
                                             'juices': juices,
                                             'soft_drinks': soft_drinks
                                             })


class OrderView(View):

    def post(self, request):
        form = OrderForm(request.POST)
        if form.is_valid():
            new = Order.objects.create(
                                       # dish_name=request.POST.get('dish_{{dish.id}}'),
                                       # drink=request.POST.get('drink_{{drink.id}}'),
                                       name_surname=request.POST.get('name_surname'),
                                       address=request.POST.get('address'),
                                       email=request.POST.get('email'),
                                       phone_number=request.POST.get('phone_number'),
                                       self_pickup=request.POST.get('self_pickup')
                                       # dish_order_quantity=request.POST.get('dish_order_quantity'),
                                       # wine_order_quantity=request.POST.get('wine_order_quantity'),
                                       # drink_order_quantity=request.POST.get('drink_order_quantity'),
                                       # juice_order_quantity=request.POST.get('juice_order_quantity'),
                                       # beer_order_quantity=request.POST.get('beer_order_quantity'),
                                       )
        # print(request.POST.keys())
        # print(request.POST)
        # keys = ' '.join(request.POST.keys())
        # print(keys)  # to mój komentarz
        for e in request.POST.keys():
            print(e, request.POST.get(e))
        return redirect('order')

    def get(self, request):
        form = OrderForm
        dishes = Dish.objects.all()
        wines = Drinks.objects.filter(drink_type=3)
        beers = Drinks.objects.filter(drink_type=4)
        juices = Drinks.objects.filter(drink_type=5)
        soft_drinks = Drinks.objects.filter(drink_type=1)
        drinks = Drinks.objects.filter(drink_type=2)
        # for e in drinks:
        #     print (vars(e))
        # print(len(dishes), len(wines), len(beers), juices, soft_drinks , drinks)
        return render(request, 'order.html', {'dishes': dishes,
                                              'drinks': drinks,
                                              'wines': wines,
                                              'beers': beers,
                                              'juices': juices,
                                              'soft_drinks': soft_drinks,
                                              'form': form})


class BookSeatView(View):
    def get(self, request):
        form = BookSeatForm
        return render(request, 'book_a_seat.html', {'form': form})

    def post(self, request):
        form = BookSeatForm(request.POST)
        if form.is_valid():
            new = BookSeat.objects.create(date=request.POST.get('date'),
                                          time=request.POST.get('time'),
                                          guest_number=request.POST.get('guest_number'),
                                          name_surname=request.POST.get('name_surname'),
                                          email=request.POST.get('email'),
                                          phone=request.POST.get('phone'),
                                          message=request.POST.get('message')
                                          )
        return redirect('book')


class AboutView(View):
    def get(self, request):
        return render(request, 'about.html')


class ContactView(View):
    def get(self, request):
        form = ContactForm
        return render(request, 'contact.html', {'form': form})

    def post(self, request):
        form = ContactForm(request.POST)
        if form.is_valid():
            new = Contact.objects.create(subject=request.POST.get('subject'),
                                         content=request.POST.get('content'),
                                         contact_details=request.POST.get('contact_details'),
                                         email=request.POST.get('email'),
                                         phone_number=request.POST.get('phone_number')
                                         )
            return redirect('contact')

            # class OrderView(View):
            #     def get(self, request):
            #         # form = OrderForm
            #         dishes = Dish.objects.all()
            #         wines = Drinks.objects.filter(drink_type=3)
            #         beers = Drinks.objects.filter(drink_type=4)
            #         juices = Drinks.objects.filter(drink_type=5)
            #         soft_drinks = Drinks.objects.filter(drink_type=1)
            #         drinks = Drinks.objects.filter(drink_type=2)
            #         return render(request, 'order.html', {'dishes': dishes,
            #                                              'drinks': drinks,
            #                                              'wines': wines,
            #                                              'beers': beers,
            #                                              'juices': juices,
            #                                              'soft_drinks': soft_drinks
            #                                              })


# class DishView(View):
#     def get(self, request):
#         form = DishForm
#         return render(request, 'form.html', {'form': form})
#     def post(self, request):
#         form = DishForm(request.POST)
#         if form.is_valid():
#             new = Dish.objects.create(dish_name = request.POST.get('dish_name'),
#                                       price = request.POST.get('price'),
#                                       ingredient = request.POST.get('ingredient'))
#         return redirect ('dish')
# #
# class IngredientView(View):
#     def get(self, request):
#         form = IngredientForm
#         return render(request, 'form.html', {'form': form})
#     def post(self, request):
#         form = IngredientForm(request.POST)
#         if form.is_valid():
#             new = Ingredient.objects.create(ingredient_name = request.POST.get('ingredient_name'))
#             dish_id = new.dish_id
#         return redirect ('ingredient')
#
# class DrinksView(View):
#     def get(self, request):
#         form = DrinksForm
#         return render(request, 'form.html', {'form': form})
#     def post(self, request):
#         form = DrinksForm(request.POST)
#         if form.is_valid():
#             new = Drinks.objects.create(drink_type = request.POST.get('drink_type'),
#                                         drink_volume = request.POST.get('drink_volume'),
#                                         wine_colors = request.POST.get('wine_colors'),
#                                         wine_sweetness = request.POST.get('wine_sweetness'),
#                                         drink_name = request.POST.get('drink_name'),
#                                         price=request.POST.get('price')
#                                         )
#         return redirect ('drinks')

restaurant/templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>About Delicious</title>

    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>
<body>

    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">

            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="home">Home</a>
            </div>

            <div class="collapse navbar-collapse" id="topNavBar">
                <ul class="nav navbar-nav">
                    <li class="">
                        <a href="menu">
                            <span class="glyphicon glyphicon-book"></span>&nbsp;Menu
                        </a>
                    </li>
                    <li class="">
                        <a href="order">
                            <span class="glyphicon glyphicon-shopping-cart"></span>&nbsp;Order Meal
                        </a>
                    </li>
                    <li class="">
                        <a href="book">
                            <span class="glyphicon glyphicon-calendar"></span>&nbsp;Book a Seat
                        </a>
                    </li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    <li class="">
                        <a href="about">
                            <span class="glyphicon glyphicon-info-sign"></span>&nbsp;About Us
                        </a>
                    </li>
                    <li class="">
                        <a href="contact">
                            <span class="glyphicon glyphicon-earphone"></span>&nbsp;Contact
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <h1>Delicious</h1>
    <div id="image"></div>

    <div id="map" style="width:400px;height:400px;"></div>

    <script>
    function myMap() {
      var mapCanvas = document.getElementById("map");
      var mapOptions = {
        center: new google.maps.LatLng(51.410153, 19.668649), zoom:15
      };
      var map = new google.maps.Map(mapCanvas, mapOptions);
    }
    </script>

    <script src="https://maps.googleapis.com/maps/api/js?key= AIzaSyBEq0jX7yzk2k9eKR09Vy71gPAEMKQgbks&callback=myMap"></script>

    <div class="contact_details">
        <p>
            <strong>
            Restauracja "Delicious"<br>
            ul. Długa 15<br>
            00-200 Piotrków<br>
            </strong>
        </p>

    </div>

    <footer>
		<strong>
            <a href="home">Home</a>
            &#8208;
            <a href="menu">Menu</a>
            &#8208;
            <a href="order">Order Meal</a>
            &#8208;
            <a href="book">Book a Seat</a>
            &#8208;
            <a href="about">About Us</a>
            &#8208;
            <a href="contact">Contact</a><br>
            {{ now }}
		</strong>
    </footer>


<script src="https://code.jquery.com/jquery-2.1.3.min.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<!--<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap/min.js"></script>-->
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
</body>
</html>

restaurant/templates/book_a_seat.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Book a seat at Delicious</title>

    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>
<body>

    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">

            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="home">Home</a>
            </div>

            <div class="collapse navbar-collapse" id="topNavBar">
                <ul class="nav navbar-nav">
                    <li class="">
                        <a href="menu">
                            <span class="glyphicon glyphicon-book"></span>&nbsp;Menu
                        </a>
                    </li>
                    <li class="">
                        <a href="order">
                            <span class="glyphicon glyphicon-shopping-cart"></span>&nbsp;Order Meal
                        </a>
                    </li>
                    <li class="">
                        <a href="book">
                            <span class="glyphicon glyphicon-calendar"></span>&nbsp;Book a Seat
                        </a>
                    </li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    <li class="">
                        <a href="about">
                            <span class="glyphicon glyphicon-info-sign"></span>&nbsp;About Us
                        </a>
                    </li>
                    <li class="">
                        <a href="contact">
                            <span class="glyphicon glyphicon-earphone"></span>&nbsp;Contact
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <h1>Delicious</h1>
    <div id="image"></div>

        <div class="contact_form">
            <form method="POST">
            {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="wyślij">
            </form>
        </div>


    <footer>
		<strong id="1">
            <a href="home">Home</a>
            &#8208;
            <a href="menu">Menu</a>
            &#8208;
            <a href="order">Order Meal</a>
            &#8208;
            <a href="book">Book a Seat</a>
            &#8208;
            <a href="about">About Us</a>
            &#8208;
            <a href="contact">Contact</a><br>
            {{ now }}
		</strong>
    </footer>

<script src="https://code.jquery.com/jquery-2.1.3.min.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<!--<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap/min.js"></script>-->
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
</body>
</html>

restaurant/templates/menu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home Page</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>
<body>

    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">

            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="home">Home</a>
            </div>

            <div class="collapse navbar-collapse" id="topNavBar">
                <ul class="nav navbar-nav">
                    <li class="">
                        <a href="menu">
                            <span class="glyphicon glyphicon-book"></span>&nbsp;Menu
                        </a>
                    </li>
                    <li class="">
                        <a href="order">
                            <span class="glyphicon glyphicon-shopping-cart"></span>&nbsp;Order Meal
                        </a>
                    </li>
                    <li class="">
                        <a href="book">
                            <span class="glyphicon glyphicon-calendar"></span>&nbsp;Book a Seat
                        </a>
                    </li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    <li class="">
                        <a href="about">
                            <span class="glyphicon glyphicon-info-sign"></span>&nbsp;About Us
                        </a>
                    </li>
                    <li class="">
                        <a href="contact">
                            <span class="glyphicon glyphicon-earphone"></span>&nbsp;Contact
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <h1>Delicious</h1>
    <!--<div id="image"></div>-->

    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
        <li data-target="#myCarousel" data-slide-to="4"></li>
      </ol>
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <img class="first-slide" src="static/images/dish.jpg" alt="First slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Dnia główne:</h1>
              <p>
                {% for dish in dishes %}
                {{ dish.dish_name }} {{ dish.price }}<br>
                {% endfor %}
              </p>
              <!--<p><a class="btn btn-lg btn-primary" href="#" role="button">Sign up today</a></p>-->
            </div>
          </div>
        </div>
        <div class="item">
          <img class="second-slide" src="static/images/drinks.jpg" alt="Second slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Drinki:</h1>
              <p>
                {% for drink in drinks %}
                {{ drink.drink_name }} {{ drink.price }}<br>
                {% endfor %}
              </p>
              <!--<p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>-->
            </div>
          </div>
        </div>
        <div class="item">
          <img class="third-slide" src="static/images/wino.jpg" alt="Third slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Wina:</h1>
              <p>
                {% for wine in wines %}
                {{ wine.drink_name }} {{ wine.get_drink_volume_display }} {{ wine.price }}<br>
                {% endfor %}
              </p>
              <!--<p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>-->
            </div>
          </div>
        </div>
        <div class="item">
          <img class="second-slide" src="static/images/juice.jpg" alt="Second slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Soki:</h1>
              <p>
                {% for juice in juices %}
                {{ juice.drink_name }} {{ juice.price }}<br>
                {% endfor %}
              </p>
              <!--<p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>-->
            </div>
          </div>
        </div>
        <div class="item">
          <img class="third-slide" src="static/images/piwo.jpg" alt="Third slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Piwa:</h1>
              <p>
                {% for beer in beers %}
                {{ beer.drink_name }} {{ beer.price }}<br>
                {% endfor %}
              </p>
              <!--<p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>-->
            </div>
          </div>
        </div>
      </div>

      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>

    <footer>
		<strong>
            <a href="home">Home</a>
            &#8208;
            <a href="menu">Menu</a>
            &#8208;
            <a href="order">Order Meal</a>
            &#8208;
            <a href="book">Book a Seat</a>
            &#8208;
            <a href="about">About Us</a>
            &#8208;
            <a href="contact">Contact</a><br>
            {{ now }}
		</strong>
    </footer>

<script src="https://code.jquery.com/jquery-2.1.3.min.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>


</body>
</html>